# Site settings
title: FullGC
email: dani.shemesh@hotmail.com
author: Dani Shemesh
description: "A blog about backend development, Scala development and devops"
baseurl: ""
url: "http://fullgc.github.io"
github_username: FullGC
linkedin_username: dani-shemesh
# Build settings
markdown: kramdown
highlighter:
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

plugins:
  - jekyll-seo-tag

disqus: FullGC