# Site settings
title: FullGC
email: dani.shemesh@hotmail.com
author: FullGC
description: "A blog about backend development, Scala development and devops"
baseurl: ""
url: "http://fullgc.github.io"
github_username:  FullGC
linkedin_username: dani-shemesh

# Build settings
markdown: kramdown
highlighter:
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap

disqus: FullGC

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: dani.shemesh@hotmail.com
  facebook: dani.shemesh.397
  flickr:
  github: FullGC
  instagram:
  linkedin: dani-shemesh
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
