# Site settings
title: FullGC.github.io
email: dani.shemesh@hotmail.com
author: Daniel Shemesh
description: "A blog about backend development, mobile development, and entrepreneurship"
baseurl: ""
url: "http://fullgc.github.io"
github_username:  FullGC
linkedin_username: dani-shemesh

# Build settings
markdown: kramdown
highlighter:
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap

disqus: FullGC
